Repository tmforum-oda/oda-canvas, pull requests merged in 2021-03, with the labels that each got.

#12 Update CRD to v1alpha2 and add support for Keycloak and security controller
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/ISSUE_TEMPLATE/test.md
  .github/Issues.PNG
  .gitignore
  canvas/charts/controller/crds/peering.yaml
  canvas/charts/controller/templates/_helpers.tpl
  canvas/charts/controller/templates/configMap.yaml
  canvas/charts/controller/templates/deployment.yaml
  canvas/charts/controller/templates/peering.yaml
  canvas/charts/controller/templates/rbac.yaml
  canvas/charts/controller/templates/secret.yaml
  canvas/charts/controller/templates/service.yaml
  canvas/charts/controller/values.yaml
  canvas/charts/keycloak/.helmignore
  canvas/charts/keycloak/Chart.lock
  canvas/charts/keycloak/Chart.yaml
  canvas/charts/keycloak/templates/_helpers.tpl
  canvas/charts/keycloak/templates/configMap.yaml
  canvas/charts/keycloak/templates/deployment.yaml
  canvas/charts/keycloak/templates/ingress.yaml
  canvas/charts/keycloak/templates/secret.yaml
  canvas/charts/keycloak/templates/service.yaml
  canvas/charts/keycloak/values.yaml
  canvas/crds/oda-api-crd.yaml
  canvas/crds/oda-component-crd.yaml
  canvas/templates/_helpers.tpl
  canvas/templates/namespace-canvas.yaml
  canvas/templates/namespace-default.yaml
  canvas/values.yaml
Labels: feature

#15 fix helm repo addr
  install_canvas.sh
Labels: bug-fix

#17 refactor(chart): move images to tmforumodacanvas
  canvas/charts/controller/values.yaml
Labels: refactor
