Repository tmforum-oda/oda-canvas, pull requests merged in 2023-11, with the labels that each got.

#123 Add BDD/TDD for Security Operator role check
  .gitignore
  compliance-test-kit/BDD-and-TDD/README.md
  compliance-test-kit/BDD-and-TDD/features/UC001-F001-Bootstrap-Secure-User-and-Role-Information-Communication.feature
  compliance-test-kit/BDD-and-TDD/features/UC001-F001-Bootstrap-Support-Standard-Defined-Role-for-Canvas-Admin.feature
  compliance-test-kit/BDD-and-TDD/features/UC001-F002-Bootstrap-Grouping-Permission-Specification-Sets-into-Business-Roles-in-Identity-Management-Solution.feature
  compliance-test-kit/BDD-and-TDD/features/UC001-F003-Bootstrap-Secure-User-and-Role-Information-Communication.feature
  compliance-test-kit/BDD-and-TDD/features/steps/TDD-implementation-steps.js
  compliance-test-kit/BDD-and-TDD/identity-manager-utils-keycloak/identity-manager-utils-keycloak.js
  compliance-test-kit/BDD-and-TDD/identity-manager-utils-keycloak/package.json
  compliance-test-kit/BDD-and-TDD/package.json
  package-lock.json
Labels: feature, help wanted, Sprint 3

#124 Issue85 - improved description
  compliance-test-kit/BDD-and-TDD/README.md
  compliance-test-kit/BDD-and-TDD/features/UC001-F001-Bootstrap-Apply-Standard-Defined-Role-to-Canvas-Admin-user.feature
Labels: documentation

#126 Issue 125 partyrole
  compliance-test-kit/BDD-and-TDD/features/UC002-F001-Expose-APIs-Create-API-Resource.feature
  compliance-test-kit/BDD-and-TDD/features/UC002-F002-Expose-APIs-Publish-API-Resource-URL.feature
  compliance-test-kit/BDD-and-TDD/features/UC002-F003-Expose-APIs-Verify-API-implementation-is-ready.feature
  installation/oda-crds/templates/oda-component-crd.yaml
  source/operators/README.md
  usecase-library/pumlFiles/bootstrap-role.puml
Labels: refactor
