Repository tmforum-oda/oda-canvas, pull requests merged in 2024-02, with the labels that each got.

#170 Update the helm chart release functionality
  .github/workflows/label-pullrequest.yml
  .github/workflows/release.yml
  .nojekyll
  charts/canvas-namespaces/.helmignore
  charts/canvas-namespaces/Chart.yaml
  charts/canvas-namespaces/templates/_helpers.tpl
  charts/canvas-namespaces/templates/namespace-cert-manager.yaml
  charts/canvas-namespaces/templates/namespace-default.yaml
  charts/canvas-oda/.helmignore
  charts/canvas-oda/Chart.lock
  charts/canvas-oda/Chart.yaml
  charts/canvas-oda/README.md
  charts/canvas-oda/templates/_helpers.tpl
  charts/canvas-oda/values.yaml
  charts/cert-manager-init/.helmignore
  charts/cert-manager-init/Chart.lock
  charts/cert-manager-init/Chart.yaml
  charts/cert-manager-init/templates/_helpers.tpl
  charts/cert-manager-init/templates/certificate.yaml
  charts/cert-manager-init/templates/cluster_issuer.yaml
  charts/cert-manager-init/templates/issuer.yaml
  charts/cert-manager-init/templates/webhook.yaml
  charts/cert-manager-init/values.yaml
  charts/controller/Chart.yaml
  charts/controller/crds/peering-cdrs.yaml
  charts/controller/templates/_helpers.tpl
  charts/controller/templates/configMap.yaml
  charts/controller/templates/deployment.yaml
  charts/controller/templates/ingressGateway.yaml
  charts/controller/templates/peering.yaml
  charts/controller/templates/rbac.yaml
  charts/controller/templates/secret.yaml
  charts/controller/templates/service.yaml
  charts/controller/values.yaml
  charts/oda-crds/Chart.yaml
  charts/oda-crds/templates/oda-api-crd.yaml
  charts/oda-crds/templates/oda-component-crd.yaml
  charts/oda-crds/templates/oda-publishednotification-crd.yaml
  charts/oda-crds/templates/oda-subscribednotification-crd.yaml
  charts/oda-webhook/.helmignore
  charts/oda-webhook/Chart.yaml
  charts/oda-webhook/templates/_helpers.tpl
  charts/oda-webhook/templates/deployment-componentcrdwebhook.yaml
  charts/oda-webhook/templates/service-componentcrdwebhook.yaml
  charts/oda-webhook/values.yaml
  installation/README.md
Labels: feature

#172 164 crd kind definition should be camelcase
  charts/canvas-namespaces/Chart.yaml
  charts/canvas-oda/Chart.lock
  charts/canvas-oda/Chart.yaml
  charts/canvas-oda/values.yaml
  charts/cert-manager-init/Chart.yaml
  charts/controller/values.yaml
  charts/oda-crds/Chart.yaml
  charts/oda-crds/templates/oda-api-crd.yaml
  charts/oda-crds/templates/oda-component-crd.yaml
  charts/oda-webhook/Chart.yaml
  source/operators/apiOperatorIstio/apiOperatorIstio.py
  source/operators/buildControllers.sh
  source/operators/componentOperator/componentOperator.py
  source/operators/securityController/securityControllerKeycloak.py
Labels: bug-fix, feature

#185 Improve install doc
  installation/README.md
  installation/precheck.sh
Labels: documentation

#183 adapt changed case in kind
  compliance-test-kit/BDD-and-TDD/testData/productcatalog-enhanced-v1beta2/templates/component-productcatalog.yaml
  compliance-test-kit/BDD-and-TDD/testData/productcatalog-v1alpha4/templates/component-productcatalog.yaml
  compliance-test-kit/BDD-and-TDD/testData/productcatalog-v1beta1/templates/component-productcatalog.yaml
  compliance-test-kit/BDD-and-TDD/testData/productcatalog-v1beta2/templates/component-productcatalog.yaml
  source/operators/tests/c_deleted.yaml
  source/operators/tests/c_mod_exposedapi.yaml
  source/operators/tests/c_mod_secapi.yaml
  source/operators/tests/c_original.yaml
Labels: bug-fix
