Repository tmforum-oda/oda-canvas, pull requests merged in 2024-01, with the labels that each got.

#141 canvas portal installation
  canvas-portal/README.md
  canvas-portal/charts/.helmignore
  canvas-portal/charts/Chart.yaml
  canvas-portal/charts/templates/NOTES.txt
  canvas-portal/charts/templates/_helpers.tpl
  canvas-portal/charts/templates/deployment.yaml
  canvas-portal/charts/templates/ingress.yaml
  canvas-portal/charts/templates/rolebindings.yaml
  canvas-portal/charts/templates/roles.yaml
  canvas-portal/charts/templates/service.yaml
  canvas-portal/charts/templates/serviceaccount.yaml
  canvas-portal/charts/values.yaml
Labels: feature

#144 Merging Canvas Portal into feature branch
  canvas-portal/README.md
  canvas-portal/charts/.helmignore
  canvas-portal/charts/Chart.yaml
  canvas-portal/charts/templates/NOTES.txt
  canvas-portal/charts/templates/_helpers.tpl
  canvas-portal/charts/templates/deployment.yaml
  canvas-portal/charts/templates/ingress.yaml
  canvas-portal/charts/templates/rolebindings.yaml
  canvas-portal/charts/templates/roles.yaml
  canvas-portal/charts/templates/service.yaml
  canvas-portal/charts/templates/serviceaccount.yaml
  canvas-portal/charts/values.yaml
Labels: documentation

#145 Some small changes and reformattings
  installation/README.md
Labels: documentation

#115 installation/README.md: fix formatting/typos
  installation/README.md
Labels: documentation

#155 153 utilities upgrade component viewer utility to latest v1beta3 spec version
  source/utilities/component-viewer/README.md
  source/utilities/component-viewer/index.js
  source/utilities/component-viewer/package-lock.json
  source/utilities/component-viewer/package.json
Labels: refactor

#158 feat(dev container): Add dev container configuration
  .devcontainer/devcontainer.json
  devcontainer.md
Labels: feature

#150 Issue 138 documentation improvements
  canvas-portal/README.md
  canvas-portal/charts/templates/roles.yaml
  installation/README.md
Labels: documentation
